// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"NetVision/domain/model"
	app_configuration2 "NetVision/domain/model/app_configuration"
	"NetVision/domain/service"
	"NetVision/infrastructure/app_configuration"
	"NetVision/infrastructure/configuration"
	"NetVision/infrastructure/factory"
	"NetVision/presentation/capture"
	"NetVision/presentation/server"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitContainer(filePath string) (*Container, error) {
	appConfiguration := app_configuration.LoadAppConfig(filePath)
	captureController := capture.NewCaptureController()
	serverConfigurationMarshal := configuration.NewServerConfigurationMarshal(appConfiguration)
	clientConfigurationMarshal := configuration.NewClientConfigurationMarshal(appConfiguration)
	fileFactory := factory.NewFileFactory()
	configurationGenerateService := service.NewConfigurationGenerateService(appConfiguration, serverConfigurationMarshal, clientConfigurationMarshal, fileFactory)
	serverController := server.NewServerController(configurationGenerateService)
	container := &Container{
		AppConfig:         appConfiguration,
		CaptureController: captureController,
		ServerController:  serverController,
	}
	return container, nil
}

// wire.go:

// infrastructure
var infrastructureSet = wire.NewSet(app_configuration.LoadAppConfig, configuration.NewServerConfigurationMarshal, wire.Bind(new(service.IServerConfigurationMarshal), new(*configuration.ServerConfigurationMarshal)), configuration.NewClientConfigurationMarshal, wire.Bind(new(service.IClientConfigurationMarshal), new(*configuration.ClientConfigurationMarshal)), factory.NewFileFactory, wire.Bind(new(model.IFileFactory), new(*factory.FileFactory)))

// domain service
var domainServiceSet = wire.NewSet(service.NewConfigurationGenerateService)

// presentation
var presentationSet = wire.NewSet(capture.NewCaptureController, server.NewServerController)

type Container struct {
	AppConfig         *app_configuration2.AppConfiguration
	CaptureController *capture.CaptureController
	ServerController  *server.ServerController
}
