// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	app_configuration2 "NetVision/domain/model/app_configuration"
	"NetVision/infrastructure/app_configuration"
	"NetVision/presentation/capture"
	"NetVision/presentation/server"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitContainer(filePath string) (*Container, error) {
	appConfiguration := app_configuration.LoadAppConfig(filePath)
	captureController := capture.NewCaptureController()
	serverController := server.NewServerController()
	container := &Container{
		AppConfig:         appConfiguration,
		CaptureController: captureController,
		ServerController:  serverController,
	}
	return container, nil
}

// wire.go:

// infrastructure
var infrastructureSet = wire.NewSet(app_configuration.LoadAppConfig)

// presentation
var presentationSet = wire.NewSet(capture.NewCaptureController, server.NewServerController)

type Container struct {
	AppConfig         *app_configuration2.AppConfiguration
	CaptureController *capture.CaptureController
	ServerController  *server.ServerController
}
